name: Update Keys

on:
  push:
    branches:
      - main

jobs:
  update_keys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Raw File
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" > access_token.txt
          python update_keys.py "${{ github.event.inputs.keys }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add license_keys.txt
          git commit -m "Update license keys"
          git push
