name: Update Keys

on:
  push:
    branches:
      - main

jobs:
  update_keys:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Update Keys
      run: python update_keys.py "${GITHUB_ACCESS_TOKEN}"
